#!/bin/sh

#АВТОСТАРТ
sxhkd &
numlockx &
nitrogen --restore &
~/.config/polybar/launch.sh &
picom &
xsetroot -cursor_name left_ptr &
discord &
telegram-desktop &
google-chrome-stable &
alacritty &
pycharm &
blueberry &
pavucontrol &
todoist &
min &

#ВОРКСПЕЙСЫ
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc desktop 1 --to-monitor DP-4
bspc desktop 2 --to-monitor DP-4
bspc desktop 3 --to-monitor DP-0
bspc desktop 4 --to-monitor HDMI-0
bspc desktop 5 --to-monitor HDMI-0
bspc desktop 6 --to-monitor DP-4
bspc desktop 7 --to-monitor DP-4
bspc desktop 8 --to-monitor DP-4
bspc desktop 9 --to-monitor HDMI-0
bspc desktop 10 --to-monitor HDMI-0
bspc desktop Desktop --remove
bspc desktop Desktop --remove

#РАМКИ И ГАПСЫ
bspc config border_width         0
bspc config window_gap          10

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#d8dee9"

#ЦВЕТ ПРОСТРАНСТВА ПРИ ВЫБОРЕ ПОЛОЖЕНИЯ НОВОГО ОКНАЫ
bspc config presel_feedback_color "fd2e59"

#ПРИ ПОМОЩИ ЭТОЙ ХРЕНИ МОЖНО СДЕЛАТЬ ГАПСЫ ТОЛЬКО МЕЖДУ ОКНАМИ
#bspc config window_gap $gap;
#bspc config top_padding -$(($gap+2))
#bspc config left_padding -$(($gap+2))
#bspc config right_padding -$(($gap+4))
#bspc config bottom_padding $(($PANEL_HEIGHT-$gap))

#КОФИЦИЕНТ РАЗДЕЛЕНИЯ, СКОЛЬКО ПРОЦЕНТОВ ОСТАНЕТСЯ ОТ РОДИТЕЛЬСКОГО ОКНА ПРИ ОТКРЫТИИ НОВОГО
bspc config split_ratio          0.5

#ФОКУС ОКНА НАВЕДЕНИЕМ КУРСОРА
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

#РЕЖИМ МОНОКЛЯ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config single_monocle	     false

#ОТКЛЮЧЕНИЕ ГАПСОВ РАМОК И ОТСТУПОВ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

#СХЕМЫ СОГЛАСНО КОТОРЫМ БУДУТ ОТКРЫВАТСЯ ОКНА
#bspc config automatic_scheme	spiral

#ПРАВИЛА ОКОН
bspc rule -a TelegramDesktop  follow=off desktop='4'
bspc rule -a discord  follow=off desktop='4'
bspc rule -a Google-chrome follow=off desktop='5'
bspc rule -a jetbrains-pycharm follow=off desktop='2'
bspc rule -a blueberry.py follow=off desktop='6'
bspc rule -a pavucontrol follow=off desktop='6'
bspc rule -a todoist follow=off desktop='1'
bspc rule -a steam follow=off desktop='7'
bspc rule -a "keeper password manager" follow=off desktop='5'
